on: "3"

services:
  traefik-proxy:
    image: traefik:latest
    container_name: traefik-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Africa/Lome
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik_dynamic.yml:/traefik_dynamic.yml
      - ./acme.json:/acme.json
      - ./access.log:/access.log
    restart: always

networks:
  default:
    external:
      name: traefik-proxy
