version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always
    environment:
      MYSQL_DATABASE: woodini
      # So you don't have to use root, but you can if you like
      MYSQL_USER: seneca
      # You can use whatever password you like
      MYSQL_PASSWORD: AMGTuVXKgw983jyXh
      # Password for root access
      MYSQL_ROOT_PASSWORD: 9CcZ7zT3G0assvQjLe4EsgMv
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '5050:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - database-mysql:/var/lib/mysql
# Names our volume
volumes:
  database-mysql:
networks:
  default:
    external:
      name: database-node